---
title: "Course project"
author: "Ivan Zarudny, Egor Manin"
date: "January 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(ggdendro)
library(spatstat)
library(forecast)
library(lubridate)
```

```{r}
load('../riaa.Rda')
```

# Dataset overview

## Creating heatmap
```{r}
ggplot(data = table, aes(x=Release.date, y=Genre)) +
  xlim(as.Date('2000-01-01'), as.Date('2018-12-31')) +
  geom_raster(aes(fill=table$Certified.Units)) +
  ggtitle(label='Heatmap of certified units', subtitle='From 2010 till end of 2018') +
  xlab(label='Release date') +
  ylab(label='Genre') +
  theme(legend.position='bottom') +
  scale_fill_viridis_c(
    direction = 1,
    begin = 0.4,
    end = 0.8,
    name = 'Certified units',
    guide = guide_colorbar(
      direction = 'horizontal',
      barheight = unit(2, units='mm'),
      barwidth = unit(50, units='mm'),
      draw.ulim = F,
      title.position = 'top',
      title.hjust = 0.5,
      label.hjust = 0.5
    )
  )
```

## Slice for genre POP
```{r}
table %>%
  filter(Genre == 'POP') %>%
  ggplot(., aes(x=Release.date, y=Certified.Units)) +
    xlim(as.Date('2010-01-01'), as.Date('2018-12-31')) +
    ylim(0, 1.5e7) +
    geom_line() +
    ggtitle(label='Certified units for genre POP', subtitle='From 2010 till end of 2018') +
    xlab(label='Release date') +
    ylab(label='Certified units')
```

# Creating models
Using genre POP as reference

## First model

```{r}
table %>%
  filter(Genre == 'POP') %>%
  select(c(Certified.Units, Release.date)) %>%
  group_by(Release.date=floor_date(Release.date, "month")) %>%
  summarise(Certified.Units=sum(Certified.Units)) %>%
  arrange(Release.date) %>%
  select(c(Certified.Units)) %>%
  ts(., start=2000, end=2018+11/12, frequency=12) -> timeseries

ggseasonplot(timeseries)

model.train <- window(timeseries, start=2000, end=2015)
model.test <- window(timeseries, start=2015+1/12, end=2018+11/12)

model <- Arima(model.train, seasonal=c(1,1,0), include.drift=T)
model.forecast <- forecast(model, h=length(model.test))

autoplot(model.test) +
  geom_line(data=model.forecast$mean, show.legend=F, aes(colour='red')) +
  ggtitle(label='Model forecast and actual data', subtitle='Trained model by data filtered from 2000 till end of 2018') +
  xlab(label='Release date') +
  ylab(label='Certified units')

accuracy.1 <- accuracy(model.forecast, model.test)
accuracy.1

model.full <- Arima(timeseries, seasonal=c(1,1,0), include.drift=T)
checkresiduals(model.full, plot=T)
# lag should be equals df from checkresiduals
Box.test(model.full$residuals, lag=22, type='Ljung-Box', fitdf=0)
```

```{r cleanup1, include=FALSE}
remove(list=c('timeseries', 'model.train', 'model.test', 'model', 'model.full', 'model.forecast'))
```

## Projecting certified units onto log scale
```{r}
table %>%
  filter(Genre == 'POP') %>%
  select(c(Certified.Units, Release.date)) %>%
  group_by(Release.date=floor_date(Release.date, "month")) %>%
  summarise(Certified.Units=sum(Certified.Units)) %>%
  mutate(Certified.Units=log(Certified.Units)) %>%
  arrange(Release.date) %>%
  select(c(Certified.Units)) %>%
  ts(., start=2000, end=2018+11/12, frequency=12) -> timeseries

ggseasonplot(timeseries)

model.train <- window(timeseries, start=2000, end=2015)
model.test <- window(timeseries, start=2015+1/12, end=2018+11/12)

model <- Arima(model.train, seasonal=c(1,1,0), include.drift=T)
model.forecast <- forecast(model, h=length(model.test))

autoplot(model.test) +
  geom_line(data=model.forecast$mean, show.legend=F, aes(colour='red')) +
  ggtitle(label='Model forecast and actual data', subtitle='Trained model by data filtered from 2000 till end of 2015') +
  xlab(label='Release date') +
  ylab(label='Certified units')

accuracy.2 <- accuracy(model.forecast, model.test)
accuracy.2

model.full <- Arima(timeseries, seasonal=c(1,1,0), include.drift=T)
checkresiduals(model.full, plot=T)
# lag should be equals df from checkresiduals
Box.test(model.full$residuals, lag=22, type='Ljung-Box', fitdf=0)
```

```{r cleanup2, include=FALSE}
remove(list=c('timeseries', 'model.train', 'model.test', 'model', 'model.full', 'model.forecast'))
```

## Filtering dataset from drop outs
```{r}
table %>%
  filter(Genre == 'POP') %>%
  select(c(Certified.Units, Release.date)) %>%
  group_by(Release.date=floor_date(Release.date, "month")) %>%
  summarise(Certified.Units=sum(Certified.Units)) %>%
  mutate(Certified.Units=log(Certified.Units)) %>%
  filter(Certified.Units > 13 & Certified.Units < 18) %>%
  arrange(Release.date) %>%
  select(c(Certified.Units)) %>%
  ts(., start=2000, end=2018+11/12, frequency=12) -> timeseries

ggseasonplot(timeseries)

model.train <- window(timeseries, start=2000, end=2015)
model.test <- window(timeseries, start=2015+1/12, end=2018+11/12)

model <- Arima(model.train, seasonal=c(1,1,0), include.drift=T)
model.forecast <- forecast(model, h=length(model.test))

autoplot(model.test) +
  geom_line(data=model.forecast$mean, show.legend=F, aes(colour='red')) +
  ggtitle(label='Model forecast and actual data', subtitle='Trained model by data filtered from 2000 till end of 2015') +
  xlab(label='Release date') +
  ylab(label='Certified units')

accuracy.3 <- accuracy(model.forecast, model.test)
accuracy.3

model.full <- Arima(timeseries, seasonal=c(1,1,0), include.drift=T)
checkresiduals(model.full, plot=T)
# lag should be equals df from checkresiduals
Box.test(model.full$residuals, lag=22, type='Ljung-Box', fitdf=0)
```

```{r cleanup3, include=FALSE}
remove(list=c('timeseries', 'model.train', 'model.test', 'model', 'model.full', 'model.forecast'))
```

## Projecting onto trigonometry functions
```{r}
table %>%
  filter(Genre == 'POP') %>%
  select(c(Certified.Units, Release.date)) %>%
  group_by(Release.date=floor_date(Release.date, "month")) %>%
  summarise(Certified.Units=sum(Certified.Units)) %>%
  mutate(Certified.Units=tan(Certified.Units)+10) %>%
  filter(Certified.Units > 0 & Certified.Units < 20) %>%
  arrange(Release.date) %>%
  select(c(Certified.Units)) %>%
  ts(., start=2000, end=2018+11/12, frequency=12) -> timeseries

ggseasonplot(timeseries)

model.train <- window(timeseries, start=2000, end=2015)
model.test <- window(timeseries, start=2015+1/12, end=2018+11/12)

model <- Arima(model.train, seasonal=c(1,1,0), include.drift=T)
model.forecast <- forecast(model, h=length(model.test))

autoplot(model.test) +
  geom_line(data=model.forecast$mean, show.legend=F, aes(colour='red')) +
  ggtitle(label='Model forecast and actual data', subtitle='Trained model by data filtered from 2000 till end of 2015') +
  xlab(label='Release date') +
  ylab(label='Certified units')

accuracy.4 <- accuracy(model.forecast, model.test)
accuracy.4

model.full <- Arima(timeseries, seasonal=c(1,1,0), include.drift=T)
checkresiduals(model.full, plot=T)
# lag should be equals df from checkresiduals
Box.test(model.full$residuals, lag=22, type='Ljung-Box', fitdf=0)
```

```{r cleanup4, include=FALSE}
remove(list=c('timeseries', 'model.train', 'model.test', 'model', 'model.full', 'model.forecast'))
```
